server: 
  port: 0

spring:
  application:
    name: operador-service

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

app:
  gatewayBaseUrl: ${GATEWAY_BASE_URL:http://cloud-gateway:8080}
