server:
  port: 0

spring:
  application:
    name: buscador-service
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS:http://localhost:9200}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
