server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cloud-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: buscador
          uri: lb://buscador-service
          predicates:
            - Path=/api/items, /api/items/**

        # /api/orders  -> (StripPrefix) -> /orders  (operador-service)
        - id: operador_api
          uri: lb://operador-service
          predicates:
            - Path=/api/orders, /api/orders/**

        # (opcional) también aceptar /orders directamente
        - id: operador_plain
          uri: lb://operador-service
          predicates:
            - Path=/orders, /orders/**
          # sin StripPrefix
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
